# Generated by Django 4.1 on 2023-05-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_options_alter_account_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="age",
            field=models.IntegerField(default=3),
        ),
    ]
